### PR TITLE
Did a lot of work password authenticaiton

### PR DESCRIPTION
**Pull request by CamBC-Lab**
Made most of the backend files for password authentication and functionality. Made the front-end files for starting off.

### CODE REVIEW

**Comment by ManiChams** [comment]
looks good

**Comment by Godzelduh** [comment]
Reviewed and approved

**Review by ManiChams — COMMENTED** [review]
looks good

**Review by Godzelduh — APPROVED** [review]
Looks great, approved.

**Review by Plutarch1971 — APPROVED** [review]

**Pull request merged**
